# -*- coding: utf-8 -*-
"""Financial-RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ugk-_GNcT9TCMfwEEuerbFgFVH9RyOmj
"""



import chromadb
import google.generativeai as genai
from sentence_transformers import SentenceTransformer

print("All imports successful")

from google.colab import files
uploaded = files.upload()

### configuring Gemini ###
GEMINI_API_KEY = "AQ.Ab8RN6LxL-TwuCv2PHeN76Ntb68e7U-EEjw6Qe_H16J5eD8CpA"
genai.configure(api_key=GEMINI_API_KEY)
LLM = genai.GenerativeModel("gemini-2.5-flash")



### EXTRACTING TEXT ###
import fitz

documents = []

for file_name in uploaded.keys():

    doc = fitz.open(file_name)

    text = ""

    for page in doc:
        text += page.get_text()

    documents.append({
        "company": file_name.replace(".pdf",""),
        "text": text
    })

    print(f"Finished {file_name}")

print("Loaded:", len(documents))

### CHUNKING ###


from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size = 1000,
    chunk_overlap = 200
)

chunks = []
for doc in documents:
  split_docs = splitter.split_text(doc["text"])

  for chunk in split_docs:


    chunks.append({
        "company":doc["company"],
        "text": chunk
    })
print("Total Chunks:",len(chunks))

### LOADING BGE MODEL AND GENERATING EMBEDDINGS ###
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer("BAAI/bge-small-en-v1.5")


texts = [chunk["text"] for chunk in chunks]

embedding = embedding_model.encode(
    texts,
    batch_size = 32,
    show_progress_bar = True,
    convert_to_numpy= True
)


print("Embedding shape:",embedding.shape)

### CREATAING CHROMADB AND STOREING EMBEDDINGS ###
import chromadb
vectordb = chromadb.Client()
collection = vectordb.get_or_create_collection(name = "financial_reports")


documents_text = [chunk["text"] for chunk in chunks]

metadatas = [{
    "company": chunk["company"]}
    for chunk in chunks
]


ids = [
    str(i)
    for i in range(len(chunks))
]


collection.add(
    ids = ids,
    documents = documents_text,
    embeddings = embedding.tolist(),
    metadatas = metadatas
)
print("Stored:", len(documents_text))

### BUILDING RETRIEVA FUNCTION ###
def retrieve(query , top_k=5):
  query_embedding = embedding_model.encode(query)

  results = collection.query(query_embeddings=[query_embedding.tolist()],n_results = top_k)

  retrieved = []

  for i in range(len(results["documents"][0])):
    retrieved.append({"text":results["documents"][0][i],
                      "Company":results["metadatas"][0][i]["company"]})
  return retrieved

### TESTING RETRIEVAL FUNCTION ###
docs = retrieve(
    "What are Tesla's major risks?"
)

print(docs[0]["Company"])
print(docs[0]["text"][:500])

### FINAL RAG PIPELINE INCLUDING GEMINI AND PROMPT ###
def ask_financial_assistant(question):

  docs = retrieve(question,top_k = 5)
  context = "\n\n".join(doc["text"] for doc in docs)
  sources = list(set(doc["Company"] for doc in docs))


  prompt = f"""
  You are a senior financial analyst.
  Answer ONLY using provided context.
  if the answer is not found in the context,
  state that clearly.

  CONTEXT:{context}
  QUESTION:{question}

  Provide:
  1. Detailed Answer
  2. Key Insights
  3. Sources Used
  """
  response = LLM.generate_content(prompt)

  return{"answer": response.text,
         "sources": sources}

result = ask_financial_assistant(
    "What are Tesla's major operational risks?"
)

print(result["answer"])
print(result["sources"])

result = ask_financial_assistant(
    "Compare Amazon and Microsoft's growth strategies.")
print(result["answer"])

