# -*- coding: utf-8 -*-
"""Financial-RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ugk-_GNcT9TCMfwEEuerbFgFVH9RyOmj
"""



import chromadb
import google.generativeai as genai
import streamlit as st
from sentence_transformers import SentenceTransformer

# Gemini
genai.configure(
    api_key=st.secrets["GEMINI_API_KEY"]
)

LLM = genai.GenerativeModel(
    "gemini-2.5-flash"
)

# Embedding model
embedding_model = SentenceTransformer(
    "BAAI/bge-small-en-v1.5"
)

# Load existing ChromaDB
client = chromadb.Client()

collection = client.get_or_create_collection(
    name="financial_reports"
)

collection.add(
    ids=ids,
    documents=documents_text,
    embeddings=embeddings.tolist(),
    metadatas=metadatas
)

def retrieve(query, top_k=5):

    query_embedding = embedding_model.encode(query)

    results = collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=top_k
    )

    retrieved = []

    for i in range(len(results["documents"][0])):

        retrieved.append(
            {
                "text": results["documents"][0][i],
                "company": results["metadatas"][0][i]["company"]
            }
        )

    return retrieved


def ask_financial_assistant(question):

    docs = retrieve(question)

    context = "\n\n".join(
        [doc["text"] for doc in docs]
    )

    sources = list(
        set(
            [doc["company"] for doc in docs]
        )
    )

    prompt = f"""
You are a senior financial analyst.

Answer ONLY using the provided context.

CONTEXT:
{context}

QUESTION:
{question}

Provide:
1. Detailed Answer
2. Key Insights
3. Sources Used
"""

    response = LLM.generate_content(prompt)

    return {
        "answer": response.text,
        "sources": sources
    }

